supportedK8sVersions:
  - v121
  - v122
  - v123
  - v124
  - v125
  - v126
drivers:
  - name: powermax
    configVersions:
      - configVersion: v2.6.0
        useDefaults: true
        supportedVersions:
          - version: v123
          - version: v124
          - version: v125
          - version: v126
      - configVersion: v2.5.0
        useDefaults: false
        supportedVersions:
          - version: v121
          - version: v123
          - version: v124
          - version: v125
        attacher: k8s.gcr.io/sig-storage/csi-attacher:v4.0.0
        provisioner: k8s.gcr.io/sig-storage/csi-provisioner:v3.3.0
        snapshotter: k8s.gcr.io/sig-storage/csi-snapshotter:v6.1.0
        resizer: k8s.gcr.io/sig-storage/csi-resizer:v1.6.0
        registrar: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.6.0
        external-health-monitor: gcr.io/k8s-staging-sig-storage/csi-external-health-monitor-controller:v0.7.0
      - configVersion: v2.4.0
        useDefaults: false
        supportedVersions:
          - version: v121
          - version: v122
          - version: v123
          - version: v124
        attacher: k8s.gcr.io/sig-storage/csi-attacher:v3.5.0
        provisioner: k8s.gcr.io/sig-storage/csi-provisioner:v3.2.1
        snapshotter: k8s.gcr.io/sig-storage/csi-snapshotter:v6.0.1
        resizer: k8s.gcr.io/sig-storage/csi-resizer:v1.5.0
        registrar: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.1
        external-health-monitor: gcr.io/k8s-staging-sig-storage/csi-external-health-monitor-controller:v0.6.0
  - name: unity
    configVersions:
      - configVersion: v2.6.0
        useDefaults: true
        supportedVersions:
          - version: v123
          - version: v124
          - version: v125
          - version: v126
      - configVersion: v2.5.0
        useDefaults: false
        supportedVersions:
          - version: v121
          - version: v123
          - version: v124
          - version: v125
        attacher: k8s.gcr.io/sig-storage/csi-attacher:v4.0.0
        provisioner: k8s.gcr.io/sig-storage/csi-provisioner:v3.3.0
        snapshotter: k8s.gcr.io/sig-storage/csi-snapshotter:v6.1.0
        resizer: k8s.gcr.io/sig-storage/csi-resizer:v1.6.0
        registrar: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.6.0
        external-health-monitor: gcr.io/k8s-staging-sig-storage/csi-external-health-monitor-controller:v0.7.0
      - configVersion: v2.4.0
        useDefaults: false
        supportedVersions:
          - version: v121
          - version: v122
          - version: v123
          - version: v124
        attacher: k8s.gcr.io/sig-storage/csi-attacher:v3.5.0
        provisioner: k8s.gcr.io/sig-storage/csi-provisioner:v3.2.0
        snapshotter: k8s.gcr.io/sig-storage/csi-snapshotter:v6.0.1
        resizer: k8s.gcr.io/sig-storage/csi-resizer:v1.5.0
        registrar: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.1
        external-health-monitor: gcr.io/k8s-staging-sig-storage/csi-external-health-monitor-controller:v0.6.0
  - name: vxflexos
    configVersions:
      - configVersion: v2.6.0
        useDefaults: true
        supportedVersions:
          - version: v123
          - version: v124
          - version: v125
          - version: v126
      - configVersion: v2.5.0
        useDefaults: false
        supportedVersions:
          - version: v121
          - version: v123
          - version: v124
          - version: v125
        attacher: k8s.gcr.io/sig-storage/csi-attacher:v4.0.0
        provisioner: k8s.gcr.io/sig-storage/csi-provisioner:v3.3.0
        snapshotter: k8s.gcr.io/sig-storage/csi-snapshotter:v6.1.0
        resizer: k8s.gcr.io/sig-storage/csi-resizer:v1.6.0
        registrar: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.6.0
        external-health-monitor: gcr.io/k8s-staging-sig-storage/csi-external-health-monitor-controller:v0.7.0
      - configVersion: v2.4.0
        useDefaults: false
        supportedVersions:
          - version: v121
          - version: v122
          - version: v123
          - version: v124
        attacher: k8s.gcr.io/sig-storage/csi-attacher:v3.5.0
        provisioner: k8s.gcr.io/sig-storage/csi-provisioner:v3.2.1
        snapshotter: k8s.gcr.io/sig-storage/csi-snapshotter:v6.0.1
        resizer: k8s.gcr.io/sig-storage/csi-resizer:v1.5.0
        registrar: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.1
        external-health-monitor: gcr.io/k8s-staging-sig-storage/csi-external-health-monitor-controller:v0.6.0
  - name: isilon
    configVersions:
      - configVersion: v2.6.0
        useDefaults: true
        supportedVersions:
          - version: v122
          - version: v124
          - version: v125
          - version: v126
      - configVersion: v2.5.0
        useDefaults: false
        supportedVersions:
          - version: v121
          - version: v123
          - version: v124
          - version: v125
        attacher: k8s.gcr.io/sig-storage/csi-attacher:v4.0.0
        provisioner: k8s.gcr.io/sig-storage/csi-provisioner:v3.3.0
        snapshotter: k8s.gcr.io/sig-storage/csi-snapshotter:v6.1.0
        resizer: k8s.gcr.io/sig-storage/csi-resizer:v1.6.0
        registrar: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.6.0
        external-health-monitor: gcr.io/k8s-staging-sig-storage/csi-external-health-monitor-controller:v0.7.0
      - configVersion: v2.4.0
        useDefaults: false
        supportedVersions:
          - version: v121
          - version: v122
          - version: v123
          - version: v124
        attacher: k8s.gcr.io/sig-storage/csi-attacher:v3.5.0
        provisioner: k8s.gcr.io/sig-storage/csi-provisioner:v3.2.1
        snapshotter: k8s.gcr.io/sig-storage/csi-snapshotter:v6.0.1
        resizer: k8s.gcr.io/sig-storage/csi-resizer:v1.5.0
        registrar: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.1
        external-health-monitor: gcr.io/k8s-staging-sig-storage/csi-external-health-monitor-controller:v0.6.0
  - name: powerstore
    configVersions:
      - configVersion: v2.6.0
        useDefaults: true
        supportedVersions:
          - version: v123
          - version: v124
          - version: v125
          - version: v126
      - configVersion: v2.5.0
        useDefaults: false
        supportedVersions:
          - version: v121
          - version: v123
          - version: v124
          - version: v125
        attacher: k8s.gcr.io/sig-storage/csi-attacher:v4.0.0
        provisioner: k8s.gcr.io/sig-storage/csi-provisioner:v3.3.0
        snapshotter: k8s.gcr.io/sig-storage/csi-snapshotter:v6.1.0
        resizer: k8s.gcr.io/sig-storage/csi-resizer:v1.6.0
        registrar: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.6.0
        external-health-monitor: gcr.io/k8s-staging-sig-storage/csi-external-health-monitor-controller:v0.7.0
      - configVersion: v2.4.0
        useDefaults: false
        supportedVersions:
          - version: v121
          - version: v122
          - version: v123
          - version: v124
        attacher: k8s.gcr.io/sig-storage/csi-attacher:v3.5.0
        provisioner: k8s.gcr.io/sig-storage/csi-provisioner:v3.2.1
        snapshotter: k8s.gcr.io/sig-storage/csi-snapshotter:v6.0.1
        resizer: k8s.gcr.io/sig-storage/csi-resizer:v1.5.0
        registrar: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.1
        external-health-monitor: gcr.io/k8s-staging-sig-storage/csi-external-health-monitor-controller:v0.6.0
csiSideCars:
  - name: attacher
    images:
      - version: v121
        tag: k8s.gcr.io/sig-storage/csi-attacher:v4.0.0
      - version: v122
        tag: k8s.gcr.io/sig-storage/csi-attacher:v3.5.0
      - version: v123
        tag: k8s.gcr.io/sig-storage/csi-attacher:v4.0.0
      - version: v124
        tag: k8s.gcr.io/sig-storage/csi-attacher:v4.0.0
      - version: v125
        tag: k8s.gcr.io/sig-storage/csi-attacher:v4.0.0
      - version: v126
        tag: k8s.gcr.io/sig-storage/csi-attacher:v4.0.0
  - name: provisioner
    images:
      - version: v121
        tag: k8s.gcr.io/sig-storage/csi-provisioner:v3.3.0
      - version: v122
        tag: k8s.gcr.io/sig-storage/csi-provisioner:v3.2.1
      - version: v123
        tag: k8s.gcr.io/sig-storage/csi-provisioner:v3.3.0
      - version: v124
        tag: k8s.gcr.io/sig-storage/csi-provisioner:v3.3.0
      - version: v125
        tag: k8s.gcr.io/sig-storage/csi-provisioner:v3.3.0
      - version: v126
        tag: k8s.gcr.io/sig-storage/csi-provisioner:v3.3.0
  - name: snapshotter
    images:
      - version: v121
        tag: k8s.gcr.io/sig-storage/csi-snapshotter:v6.1.0
      - version: v122
        tag: k8s.gcr.io/sig-storage/csi-snapshotter:v6.0.1
      - version: v123
        tag: k8s.gcr.io/sig-storage/csi-snapshotter:v6.1.0
      - version: v124
        tag: k8s.gcr.io/sig-storage/csi-snapshotter:v6.1.0
      - version: v125
        tag: k8s.gcr.io/sig-storage/csi-snapshotter:v6.1.0
      - version: v126
        tag: k8s.gcr.io/sig-storage/csi-snapshotter:v6.1.0
  - name: resizer
    images:
      - version: v121
        tag: k8s.gcr.io/sig-storage/csi-resizer:v1.6.0
      - version: v122
        tag: k8s.gcr.io/sig-storage/csi-resizer:v1.5.0
      - version: v123
        tag: k8s.gcr.io/sig-storage/csi-resizer:v1.6.0
      - version: v124
        tag: k8s.gcr.io/sig-storage/csi-resizer:v1.6.0
      - version: v125
        tag: k8s.gcr.io/sig-storage/csi-resizer:v1.6.0
      - version: v126
        tag: k8s.gcr.io/sig-storage/csi-resizer:v1.6.0
  - name: registrar
    images:
      - version: v121
        tag: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.6.0
      - version: v122
        tag: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.1
      - version: v123
        tag: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.6.0
      - version: v124
        tag: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.6.0
      - version: v125
        tag: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.6.0
      - version: v126
        tag: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.6.0
  - name: external-health-monitor
    images:
      - version: v121
        tag: gcr.io/k8s-staging-sig-storage/csi-external-health-monitor-controller:v0.7.0
      - version: v122
        tag: gcr.io/k8s-staging-sig-storage/csi-external-health-monitor-controller:v0.6.0
      - version: v123
        tag: gcr.io/k8s-staging-sig-storage/csi-external-health-monitor-controller:v0.7.0
      - version: v124
        tag: gcr.io/k8s-staging-sig-storage/csi-external-health-monitor-controller:v0.7.0
      - version: v125
        tag: gcr.io/k8s-staging-sig-storage/csi-external-health-monitor-controller:v0.7.0
      - version: v126
        tag: gcr.io/k8s-staging-sig-storage/csi-external-health-monitor-controller:v0.7.0
extensions:
  - name: sdc-monitor
    images:
      - version: v121
        tag: dellemc/sdc:3.6.0.6
      - version: v122
        tag: dellemc/sdc:3.6.0.6
      - version: v123
        tag: dellemc/sdc:3.6.0.6
      - version: v124
        tag: dellemc/sdc:3.6.0.6
      - version: v125
        tag: dellemc/sdc:3.6.0.6
  - name: sdc
    images:
      - version: v121
        tag: dellemc/sdc:3.6.0.6
      - version: v122
        tag: dellemc/sdc:3.6.0.6
      - version: v123
        tag: dellemc/sdc:3.6.0.6
      - version: v124
        tag: dellemc/sdc:3.6.0.6
      - version: v125
        tag: dellemc/sdc:3.6.0.6

