supportedK8sVersions:
  - v117
  - v118
  - v119
  - v120
  - v121
drivers:
  - name: powermax
    configVersions:
      - configVersion: v6
        useDefaults: true
        supportedVersions:
          - version: v119
          - version: v120
          - version: v121
      - configVersion: v5
        useDefaults: false
        supportedVersions:
          - version: v118
          - version: v119
          - version: v120
            snapshotter: k8s.gcr.io/sig-storage/csi-snapshotter:v4.0.0
        attacher: k8s.gcr.io/sig-storage/csi-attacher:v3.1.0
        provisioner: k8s.gcr.io/sig-storage/csi-provisioner:v2.1.0
        snapshotter: k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3
        resizer: quay.io/k8scsi/csi-resizer:v1.1.0
        registrar: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.1.0
      - configVersion: v4
        useDefaults: false
        supportedVersions:
          - version: v117
          - version: v118
          - version: v119
          - version: v120
        provisioner: k8s.gcr.io/sig-storage/csi-provisioner:v2.0.2
        attacher: k8s.gcr.io/sig-storage/csi-attacher:v3.0.0
        snapshotter: k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.2
        resizer: quay.io/k8scsi/csi-resizer:v1.0.0
        registrar: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.0.1
  - name: unity
    configVersions:
      - configVersion: v5
        useDefaults: true
        supportedVersions:
          - version: v119
          - version: v120
          - version: v121
      - configVersion: v4
        useDefaults: false
        supportedVersions:
          - version: v118
          - version: v119
          - version: v120
            snapshotter: k8s.gcr.io/sig-storage/csi-snapshotter:v4.0.0
        provisioner: k8s.gcr.io/sig-storage/csi-provisioner:v2.1.0
        attacher: k8s.gcr.io/sig-storage/csi-attacher:v3.1.0
        snapshotter: k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3
        resizer: quay.io/k8scsi/csi-resizer:v1.1.0
        registrar: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.1.0
      - configVersion: v3
        useDefaults: false
        supportedVersions:
          - version: v117
          - version: v118
          - version: v119
          - version: v120
        provisioner: k8s.gcr.io/sig-storage/csi-provisioner:v2.0.2
        attacher: k8s.gcr.io/sig-storage/csi-attacher:v3.0.0
        snapshotter: k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.2
        resizer: quay.io/k8scsi/csi-resizer:v1.0.0
        registrar: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.0.1
  - name: vxflexos
    configVersions:
      - configVersion: v6
        useDefaults: true
        supportedVersions:
          - version: v119
          - version: v120
          - version: v121
      - configVersion: v5
        useDefaults: true
        supportedVersions:
          - version: v119
          - version: v120
          - version: v121
      - configVersion: v4
        useDefaults: true
        supportedVersions:
          - version: v118
          - version: v119
          - version: v120
      - configVersion: v3
        useDefaults: false
        supportedVersions:
          - version: v117
          - version: v118
          - version: v119
          - version: v120
        provisioner: k8s.gcr.io/sig-storage/csi-provisioner:v2.0.2
        attacher: k8s.gcr.io/sig-storage/csi-attacher:v3.0.0
        snapshotter: k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.2
        resizer: quay.io/k8scsi/csi-resizer:v1.0.0
        registrar: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.0.1
  - name: isilon
    configVersions:
      - configVersion: v6
        useDefaults: true
        supportedVersions:
          - version: v119
          - version: v120
          - version: v121
      - configVersion: v5
        useDefaults: false
        supportedVersions:
          - version: v118
          - version: v119
          - version: v120
            snapshotter: k8s.gcr.io/sig-storage/csi-snapshotter:v4.0.0
        provisioner: k8s.gcr.io/sig-storage/csi-provisioner:v2.1.0
        attacher: k8s.gcr.io/sig-storage/csi-attacher:v3.1.0
        snapshotter: k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3
        resizer: quay.io/k8scsi/csi-resizer:v1.1.0
        registrar: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.1.0
      - configVersion: v4
        useDefaults: false
        supportedVersions:
          - version: v117
          - version: v118
          - version: v119
          - version: v120
        provisioner: k8s.gcr.io/sig-storage/csi-provisioner:v2.0.2
        attacher: k8s.gcr.io/sig-storage/csi-attacher:v3.0.0
        snapshotter: k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.2
        resizer: quay.io/k8scsi/csi-resizer:v1.0.0
        registrar: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.0.1
  - name: powerstore
    configVersions:
      - configVersion: v4
        useDefaults: true
        supportedVersions:
          - version: v119
          - version: v120
          - version: v121
      - configVersion: v3
        useDefaults: true
        supportedVersions:
          - version: v118
          - version: v119
          - version: v120
      - configVersion: v2
        useDefaults: false
        supportedVersions:
          - version: v117
          - version: v118
          - version: v119
          - version: v120
        provisioner: k8s.gcr.io/sig-storage/csi-provisioner:v2.0.2
        attacher: k8s.gcr.io/sig-storage/csi-attacher:v3.0.0
        snapshotter: k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.2
        resizer: quay.io/k8scsi/csi-resizer:v1.0.0
        registrar: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.0.1
csiSideCars:
  - name: podmon
    images:
      - version: v119
        tag: dellemc/podmon:v0.1.0
      - version: v120
        tag: dellemc/podmon:v0.1.0
      - version: v121
        tag: dellemc/podmon:v0.1.0
  - name: attacher
    images:
      - version: v117
        tag: k8s.gcr.io/sig-storage/csi-attacher:v3.0.0
      - version: v118
        tag: k8s.gcr.io/sig-storage/csi-attacher:v3.1.0
      - version: v119
        tag: k8s.gcr.io/sig-storage/csi-attacher:v3.1.0
      - version: v120
        tag: k8s.gcr.io/sig-storage/csi-attacher:v3.2.1
      - version: v121
        tag: k8s.gcr.io/sig-storage/csi-attacher:v3.2.1
  - name: provisioner
    images:
      - version: v117
        tag: k8s.gcr.io/sig-storage/csi-provisioner:v2.0.2
      - version: v118
        tag: k8s.gcr.io/sig-storage/csi-provisioner:v2.1.0
      - version: v119
        tag: k8s.gcr.io/sig-storage/csi-provisioner:v2.1.0
      - version: v120
        tag: k8s.gcr.io/sig-storage/csi-provisioner:v2.2.1
      - version: v121
        tag: k8s.gcr.io/sig-storage/csi-provisioner:v2.2.1
  - name: snapshotter
    images:
      - version: v117
        tag: k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.2
      - version: v118
        tag: k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3
      - version: v119
        tag: k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3
      - version: v120
        tag: k8s.gcr.io/sig-storage/csi-snapshotter:v4.1.0
      - version: v121
        tag: k8s.gcr.io/sig-storage/csi-snapshotter:v4.1.0
  - name: resizer
    images:
      - version: v117
        tag: quay.io/k8scsi/csi-resizer:v1.0.0
      - version: v118
        tag: quay.io/k8scsi/csi-resizer:v1.1.0
      - version: v119
        tag: quay.io/k8scsi/csi-resizer:v1.1.0
      - version: v120
        tag: k8s.gcr.io/sig-storage/csi-resizer:v1.2.0
      - version: v121
        tag: k8s.gcr.io/sig-storage/csi-resizer:v1.2.0
  - name: registrar
    images:
      - version: v117
        tag: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.0.1
      - version: v118
        tag: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.1.0
      - version: v119
        tag: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.1.0
      - version: v120
        tag: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.2.0
      - version: v121
        tag: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.2.0
extensions:
  - name: sdc-monitor
    images:
      - version: v117
        tag: dellemc/sdc:3.5.1.1
      - version: v118
        tag: dellemc/sdc:3.5.1.1-1
      - version: v119
        tag: dellemc/sdc:3.5.1.1-1
      - version: v120
        tag: dellemc/sdc:3.5.1.1-1
  - name: sdc
    images:
      - version: v117
        tag: dellemc/sdc:3.5.1.1
      - version: v118
        tag: dellemc/sdc:3.5.1.1-1
      - version: v119
        tag: dellemc/sdc:3.5.1.1-1
      - version: v120
        tag: dellemc/sdc:3.5.1.1-1
