supportedK8sVersions:
  - v117
  - v118
  - v119
  - v120
  - v121
  - v122
  - v123
  - v124
drivers:
  - name: powermax
    configVersions:
      - configVersion: v2.3.0
        useDefaults: true
        supportedVersions:
          - version: v121
          - version: v122
          - version: v123
      - configVersion: v2.2.0
        useDefaults: false
        supportedVersions:
          - version: v120
          - version: v121
          - version: v122
        attacher: k8s.gcr.io/sig-storage/csi-attacher:v3.4.0
        provisioner: k8s.gcr.io/sig-storage/csi-provisioner:v3.1.0
        snapshotter: k8s.gcr.io/sig-storage/csi-snapshotter:v5.0.1
        resizer: k8s.gcr.io/sig-storage/csi-resizer:v1.4.0
        registrar: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.0
      - configVersion: v2.1.0
        useDefaults: false
        supportedVersions:
          - version: v120
          - version: v121
          - version: v122
        attacher: k8s.gcr.io/sig-storage/csi-attacher:v3.3.0
        provisioner: k8s.gcr.io/sig-storage/csi-provisioner:v3.0.0
        snapshotter: k8s.gcr.io/sig-storage/csi-snapshotter:v4.2.1
        resizer: k8s.gcr.io/sig-storage/csi-resizer:v1.3.0
        registrar: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.3.0
      - configVersion: v2.0.0
        useDefaults: false
        supportedVersions:
          - version: v119
            provisioner: k8s.gcr.io/sig-storage/csi-provisioner:v2.1.0
            attacher: k8s.gcr.io/sig-storage/csi-attacher:v3.1.0
            snapshotter: k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3
            resizer: quay.io/k8scsi/csi-resizer:v1.1.0
            registrar: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.1.0
          - version: v120
          - version: v121
          - version: v122
        attacher: k8s.gcr.io/sig-storage/csi-attacher:v3.3.0
        provisioner: k8s.gcr.io/sig-storage/csi-provisioner:v2.2.2
        snapshotter: k8s.gcr.io/sig-storage/csi-snapshotter:v4.1.1
        resizer: k8s.gcr.io/sig-storage/csi-resizer:v1.2.0
        registrar: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.3.0
  - name: unity
    configVersions:
      - configVersion: v2.3.0
        useDefaults: true
        supportedVersions:
          - version: v121
          - version: v122
          - version: v123
          - version: v124
      - configVersion: v2.2.0
        useDefaults: false
        supportedVersions:
          - version: v121
          - version: v122
          - version: v123
        attacher: k8s.gcr.io/sig-storage/csi-attacher:v3.4.0
        provisioner: k8s.gcr.io/sig-storage/csi-provisioner:v3.1.0
        snapshotter: k8s.gcr.io/sig-storage/csi-snapshotter:v5.0.1
        resizer: k8s.gcr.io/sig-storage/csi-resizer:v1.4.0
        registrar: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.0
      - configVersion: v2.1.0
        useDefaults: false
        supportedVersions:
          - version: v120
          - version: v121
          - version: v122
        attacher: k8s.gcr.io/sig-storage/csi-attacher:v3.3.0
        provisioner: k8s.gcr.io/sig-storage/csi-provisioner:v3.0.0
        snapshotter: k8s.gcr.io/sig-storage/csi-snapshotter:v4.2.1
        resizer: k8s.gcr.io/sig-storage/csi-resizer:v1.3.0
        registrar: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.3.0
      - configVersion: v2.0.0
        useDefaults: false
        supportedVersions:
          - version: v119
            attacher: k8s.gcr.io/sig-storage/csi-attacher:v3.1.0
            provisioner: k8s.gcr.io/sig-storage/csi-provisioner:v2.1.0
            snapshotter: k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3
            registrar: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.1.0
            resizer: quay.io/k8scsi/csi-resizer:v1.1.0
          - version: v120
          - version: v121
          - version: v122
        provisioner: k8s.gcr.io/sig-storage/csi-provisioner:v2.2.2
        attacher: k8s.gcr.io/sig-storage/csi-attacher:v3.3.0
        snapshotter: k8s.gcr.io/sig-storage/csi-snapshotter:v4.1.1
        resizer: k8s.gcr.io/sig-storage/csi-resizer:v1.2.0
        registrar: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.3.0
  - name: vxflexos
    configVersions:
      - configVersion: v2.2.0
        useDefaults: true
        supportedVersions:
          - version: v121
          - version: v122
          - version: v123
      - configVersion: v2.1.0
        useDefaults: false
        supportedVersions:
          - version: v120
          - version: v121
          - version: v122
        attacher: k8s.gcr.io/sig-storage/csi-attacher:v3.3.0
        provisioner: k8s.gcr.io/sig-storage/csi-provisioner:v3.0.0
        snapshotter: k8s.gcr.io/sig-storage/csi-snapshotter:v4.2.1
        resizer: k8s.gcr.io/sig-storage/csi-resizer:v1.3.0
        registrar: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.3.0
      - configVersion: v2.0.0
        useDefaults: false
        supportedVersions:
          - version: v119
            attacher: k8s.gcr.io/sig-storage/csi-attacher:v3.1.0
            provisioner: k8s.gcr.io/sig-storage/csi-provisioner:v2.1.0
            snapshotter: k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3
            registrar: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.1.0
            resizer: quay.io/k8scsi/csi-resizer:v1.1.0
          - version: v120
          - version: v121
          - version: v122
        provisioner: k8s.gcr.io/sig-storage/csi-provisioner:v2.2.2
        attacher: k8s.gcr.io/sig-storage/csi-attacher:v3.3.0
        snapshotter: k8s.gcr.io/sig-storage/csi-snapshotter:v4.1.1
        resizer: k8s.gcr.io/sig-storage/csi-resizer:v1.2.0
        registrar: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.3.0
  - name: isilon
    configVersions:
      - configVersion: v2.3.0
        useDefaults: true
        supportedVersions:
          - version: v121
          - version: v122
          - version: v123
          - version: v124
      - configVersion: v2.2.0
        useDefaults: false
        supportedVersions:
          - version: v121
          - version: v122
          - version: v123
        attacher: k8s.gcr.io/sig-storage/csi-attacher:v3.4.0
        provisioner: k8s.gcr.io/sig-storage/csi-provisioner:v3.1.0
        snapshotter: k8s.gcr.io/sig-storage/csi-snapshotter:v5.0.1
        resizer: k8s.gcr.io/sig-storage/csi-resizer:v1.4.0
        registrar: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.0
      - configVersion: v2.1.0
        useDefaults: false
        supportedVersions:
          - version: v120
          - version: v121
          - version: v122
        attacher: k8s.gcr.io/sig-storage/csi-attacher:v3.3.0
        provisioner: k8s.gcr.io/sig-storage/csi-provisioner:v3.0.0
        snapshotter: k8s.gcr.io/sig-storage/csi-snapshotter:v4.2.1
        resizer: k8s.gcr.io/sig-storage/csi-resizer:v1.3.0
        registrar: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.3.0
      - configVersion: v2.0.0
        useDefaults: false
        supportedVersions:
          - version: v119
            attacher: k8s.gcr.io/sig-storage/csi-attacher:v3.1.0
            provisioner: k8s.gcr.io/sig-storage/csi-provisioner:v2.1.0
            snapshotter: k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3
            resizer: k8s.gcr.io/sig-storage/csi-resizer:v1.1.0
            registrar: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.1.0
          - version: v120
          - version: v121
          - version: v122
        attacher: k8s.gcr.io/sig-storage/csi-attacher:v3.3.0
        provisioner: k8s.gcr.io/sig-storage/csi-provisioner:v2.2.2
        snapshotter: k8s.gcr.io/sig-storage/csi-snapshotter:v4.1.1
        resizer: k8s.gcr.io/sig-storage/csi-resizer:v1.2.0
        registrar: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.3.0
      - configVersion: v6
        useDefaults: false
        supportedVersions:
          - version: v119
            attacher: k8s.gcr.io/sig-storage/csi-attacher:v3.1.0
            provisioner: k8s.gcr.io/sig-storage/csi-provisioner:v2.1.0
            snapshotter: k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3
            resizer: quay.io/k8scsi/csi-resizer:v1.1.0
            registrar: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.1.0
          - version: v120
          - version: v121
        attacher: k8s.gcr.io/sig-storage/csi-attacher:v3.2.1
        provisioner: k8s.gcr.io/sig-storage/csi-provisioner:v2.2.1
        snapshotter: k8s.gcr.io/sig-storage/csi-snapshotter:v4.1.0
        resizer: k8s.gcr.io/sig-storage/csi-resizer:v1.2.0
        registrar: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.2.0  
      - configVersion: v5
        useDefaults: false
        supportedVersions:
          - version: v118
          - version: v119
          - version: v120
            snapshotter: k8s.gcr.io/sig-storage/csi-snapshotter:v4.0.0
        provisioner: k8s.gcr.io/sig-storage/csi-provisioner:v2.1.0
        attacher: k8s.gcr.io/sig-storage/csi-attacher:v3.1.0
        snapshotter: k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3
        resizer: quay.io/k8scsi/csi-resizer:v1.1.0
        registrar: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.1.0
  - name: powerstore
    configVersions:
      - configVersion: v2.2.0
        useDefaults: true
        supportedVersions:
          - version: v121
          - version: v122
          - version: v123
      - configVersion: v2.1.0
        useDefaults: false
        supportedVersions:
          - version: v120
          - version: v121
          - version: v122
        provisioner: k8s.gcr.io/sig-storage/csi-provisioner:v3.0.0
        attacher: k8s.gcr.io/sig-storage/csi-attacher:v3.3.0
        snapshotter: k8s.gcr.io/sig-storage/csi-snapshotter:v4.2.1
        resizer: k8s.gcr.io/sig-storage/csi-resizer:v1.3.0
        registrar: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.3.0
      - configVersion: v2.0.0
        useDefaults: false
        supportedVersions:
          - version: v119
            attacher: k8s.gcr.io/sig-storage/csi-attacher:v3.1.0
            provisioner: k8s.gcr.io/sig-storage/csi-provisioner:v2.1.0
            snapshotter: k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3
            registrar: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.1.0
            resizer: quay.io/k8scsi/csi-resizer:v1.1.0
          - version: v120
          - version: v121
          - version: v122
        provisioner: k8s.gcr.io/sig-storage/csi-provisioner:v2.2.2
        attacher: k8s.gcr.io/sig-storage/csi-attacher:v3.3.0
        snapshotter: k8s.gcr.io/sig-storage/csi-snapshotter:v4.1.1
        resizer: k8s.gcr.io/sig-storage/csi-resizer:v1.2.0
        registrar: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.3.0
      - configVersion: v4
        useDefaults: false
        supportedVersions:
          - version: v119
            provisioner: k8s.gcr.io/sig-storage/csi-provisioner:v2.1.0
            attacher: k8s.gcr.io/sig-storage/csi-attacher:v3.2.1
            snapshotter: k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3
            resizer: quay.io/k8scsi/csi-resizer:v1.1.0
            registrar: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.1.0
          - version: v120
          - version: v121
        provisioner: k8s.gcr.io/sig-storage/csi-provisioner:v2.2.1
        attacher: k8s.gcr.io/sig-storage/csi-attacher:v3.2.1
        snapshotter: k8s.gcr.io/sig-storage/csi-snapshotter:v4.1.0
        resizer: k8s.gcr.io/sig-storage/csi-resizer:v1.2.0
        registrar: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.2.0
      - configVersion: v3
        useDefaults: false
        supportedVersions:
          - version: v118
            provisioner: k8s.gcr.io/sig-storage/csi-provisioner:v2.1.0
            attacher: k8s.gcr.io/sig-storage/csi-attacher:v3.1.0
            snapshotter: k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3
            resizer: quay.io/k8scsi/csi-resizer:v1.1.0
            registrar: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.1.0
          - version: v119
            provisioner: k8s.gcr.io/sig-storage/csi-provisioner:v2.1.0
            attacher: k8s.gcr.io/sig-storage/csi-attacher:v3.2.1
            snapshotter: k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3
            resizer: quay.io/k8scsi/csi-resizer:v1.1.0
            registrar: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.1.0
          - version: v120
        provisioner: k8s.gcr.io/sig-storage/csi-provisioner:v2.2.1
        attacher: k8s.gcr.io/sig-storage/csi-attacher:v3.2.1
        snapshotter: k8s.gcr.io/sig-storage/csi-snapshotter:v4.1.0
        resizer: k8s.gcr.io/sig-storage/csi-resizer:v1.2.0
        registrar: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.2.0
csiSideCars:
  - name: attacher
    images:
      - version: v117
        tag: k8s.gcr.io/sig-storage/csi-attacher:v3.0.0
      - version: v118
        tag: k8s.gcr.io/sig-storage/csi-attacher:v3.1.0
      - version: v119
        tag: k8s.gcr.io/sig-storage/csi-attacher:v3.1.0
      - version: v120
        tag: k8s.gcr.io/sig-storage/csi-attacher:v3.3.0
      - version: v121
        tag: k8s.gcr.io/sig-storage/csi-attacher:v3.4.0
      - version: v122
        tag: k8s.gcr.io/sig-storage/csi-attacher:v3.4.0
      - version: v123
        tag: k8s.gcr.io/sig-storage/csi-attacher:v3.4.0
      - version: v124
        tag: k8s.gcr.io/sig-storage/csi-attacher:v3.4.0
  - name: provisioner
    images:
      - version: v117
        tag: k8s.gcr.io/sig-storage/csi-provisioner:v2.0.2
      - version: v118
        tag: k8s.gcr.io/sig-storage/csi-provisioner:v2.1.0
      - version: v119
        tag: k8s.gcr.io/sig-storage/csi-provisioner:v2.1.0
      - version: v120
        tag: k8s.gcr.io/sig-storage/csi-provisioner:v3.0.0
      - version: v121
        tag: k8s.gcr.io/sig-storage/csi-provisioner:v3.1.0
      - version: v122
        tag: k8s.gcr.io/sig-storage/csi-provisioner:v3.1.0
      - version: v123
        tag: k8s.gcr.io/sig-storage/csi-provisioner:v3.1.0
      - version: v124
        tag: k8s.gcr.io/sig-storage/csi-provisioner:v3.1.0
  - name: snapshotter
    images:
      - version: v117
        tag: k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.2
      - version: v118
        tag: k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3
      - version: v119
        tag: k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3
      - version: v120
        tag: k8s.gcr.io/sig-storage/csi-snapshotter:v4.2.1
      - version: v121
        tag: k8s.gcr.io/sig-storage/csi-snapshotter:v5.0.1
      - version: v122
        tag: k8s.gcr.io/sig-storage/csi-snapshotter:v5.0.1
      - version: v123
        tag: k8s.gcr.io/sig-storage/csi-snapshotter:v5.0.1
      - version: v124
        tag: k8s.gcr.io/sig-storage/csi-snapshotter:v5.0.1
  - name: resizer
    images:
      - version: v117
        tag: quay.io/k8scsi/csi-resizer:v1.0.0
      - version: v118
        tag: quay.io/k8scsi/csi-resizer:v1.1.0
      - version: v119
        tag: quay.io/k8scsi/csi-resizer:v1.1.0
      - version: v120
        tag: k8s.gcr.io/sig-storage/csi-resizer:v1.3.0
      - version: v121
        tag: k8s.gcr.io/sig-storage/csi-resizer:v1.4.0
      - version: v122
        tag: k8s.gcr.io/sig-storage/csi-resizer:v1.4.0
      - version: v123
        tag: k8s.gcr.io/sig-storage/csi-resizer:v1.4.0
      - version: v124
        tag: k8s.gcr.io/sig-storage/csi-resizer:v1.4.0
  - name: registrar
    images:
      - version: v117
        tag: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.0.1
      - version: v118
        tag: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.1.0
      - version: v119
        tag: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.1.0
      - version: v120
        tag: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.3.0
      - version: v121
        tag: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.0
      - version: v122
        tag: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.0
      - version: v123
        tag: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.0
      - version: v124
        tag: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.0
extensions:
  - name: sdc-monitor
    images:
      - version: v117
        tag: dellemc/sdc:3.5.1.1
      - version: v118
        tag: dellemc/sdc:3.5.1.1-1
      - version: v119
        tag: dellemc/sdc:3.6
      - version: v120
        tag: dellemc/sdc:3.6
      - version: v121
        tag: dellemc/sdc:3.6
      - version: v122
        tag: dellemc/sdc:3.6
      - version: v123
        tag: dellemc/sdc:3.6
      - version: v124
        tag: dellemc/sdc:3.6
  - name: sdc
    images:
      - version: v117
        tag: dellemc/sdc:3.5.1.1
      - version: v118
        tag: dellemc/sdc:3.5.1.1-1
      - version: v119
        tag: dellemc/sdc:3.6
      - version: v120
        tag: dellemc/sdc:3.6
      - version: v121
        tag: dellemc/sdc:3.6
      - version: v122
        tag: dellemc/sdc:3.6
      - version: v123
        tag: dellemc/sdc:3.6
      - version: v124
        tag: dellemc/sdc:3.6
  - name: external-health-monitor
    images:
      - version: v120
        tag: gcr.io/k8s-staging-sig-storage/csi-external-health-monitor-controller:v0.4.0
      - version: v121
        tag: gcr.io/k8s-staging-sig-storage/csi-external-health-monitor-controller:v0.4.0
      - version: v122
        tag: gcr.io/k8s-staging-sig-storage/csi-external-health-monitor-controller:v0.4.0
      - version: v123
        tag: gcr.io/k8s-staging-sig-storage/csi-external-health-monitor-controller:v0.4.0 
      - version: v124
        tag: gcr.io/k8s-staging-sig-storage/csi-external-health-monitor-controller:v0.5.0
