general:
  vulnerabilities:
    # list of CVEs that are currently unfixed
    - CVE-2022-42898
    - CVE-2022-21698
    - CVE-2019-1010022
  bestPracticeViolations:
    # list of best practies violatied that needs a fix
    - DKL-DI-0006
    - CIS-DI-0005
    - CIS-DI-0006
    - CIS-DI-0008
    - DKL-LI-0003
    - CIS-DI-0009
