apiVersion: v1
kind: Secret
metadata:
  name: unity-creds
  # Set driver namespace
  namespace:
type: Opaque
data:
  # set username to the base64 encoded username
  username:
  # set password to the base64 encoded password
  password:
