apiVersion: storage.dell.com/v1
kind: CSIPowerStore
metadata:
  name: test-powerstore
  namespace: test-powerstore
spec:
  driver:
    # Config version for CSI PowerStore v1.1 driver
    configVersion: v1
    # Controller count. Don't increase it
    replicas: 1
    forceUpdate: false
    common:
      # Image for CSI PowerStore driver v1.1
      image: "dellemc/csi-powerstore:v1.1.0.000R"
      imagePullPolicy: IfNotPresent
      envs:
        # PowerStore Manager IP
        - name: X_CSI_POWERSTORE_ENDPOINT
          value: "https://127.0.0.1/api/rest"
        - name: X_CSI_POWERSTORE_NODE_NAME_PREFIX
          value: "csi"
        - name: X_CSI_TRANSPORT_PROTOCOL
          value: "ISCSI"
        - name: X_CSI_FC_PORTS_FILTER_FILE_PATH
          value: "/etc/fc-ports-filter"
    storageClass:
      - name: powerstore
        default: true
        reclaimPolicy: "Delete"
      - name: powerstore-xfs
        reclaimPolicy: "Delete"
        parameters:
          FsType: xfs
      - name: powerstore-nfs
        reclaimPolicy: "Delete"
        parameters:
          FsType: nfs
          nasName: nas-server
