apiVersion: storage.dell.com/v1
kind: CSIVXFlexOS
metadata:
  name: test-vxflexos
  namespace: test-vxflexos
spec:
  driver:
    configVersion: v2
    replicas: 1
    forceUpdate: false
    common:
      image: "dellemc/csi-vxflexos:v1.2.0.000R"
      imagePullPolicy: IfNotPresent
      envs:
        - name: X_CSI_VXFLEXOS_SYSTEMNAME
          value: "systemname"
        - name: X_CSI_VXFLEXOS_ENDPOINT
          value: "https://127.0.0.1"
        - name: X_CSI_VXFLEXOS_ENABLELISTVOLUMESNAPSHOT
          value: "false"
        - name: X_CSI_VXFLEXOS_ENABLESNAPSHOTCGDELETE
          value: "false"
        - name: X_CSI_DEBUG
          value: "true"
    storageClass:
      - name: vxflexos
        default: true
        reclaimPolicy: Delete
        allowVolumeExpansion: true
        parameters:
          storagepool: "pool1"
        allowedTopologies:
        - matchLabelExpressions:
        # Replace X_CSI_VXFLEXOS_SYSTEMNAME with its value
          - key: csi-vxflexos.dellemc.com/X_CSI_VXFLEXOS_SYSTEMNAME
            values:
            - csi-vxflexos.dellemc.com
      - name: vxflexos-xfs
        default: false
        reclaimPolicy: Delete
        allowVolumeExpansion: true
        parameters:
          storagepool: "pool2"
          FsType: xfs
        allowedTopologies:
        - matchLabelExpressions:
        # Replace X_CSI_VXFLEXOS_SYSTEMNAME with its value
          - key: csi-vxflexos.dellemc.com/X_CSI_VXFLEXOS_SYSTEMNAME
            values:
            - csi-vxflexos.dellemc.com
    snapshotClass:
      - name: vxflexos-snapclass
