apiVersion: storage.dell.com/v1
kind: CSIVXFlexOS
metadata:
  name: test-vxflexos
  namespace: test-vxflexos
spec:
  driver:
    configVersion: v3
    replicas: 1
    forceUpdate: false
    common:
      image: "dellemc/csi-vxflexos:v1.3.0.000R"
      imagePullPolicy: IfNotPresent
      envs:
        - name: X_CSI_VXFLEXOS_SYSTEMNAME
          value: "systemname"
        - name: X_CSI_VXFLEXOS_ENDPOINT
          value: "https://127.0.0.0"
        - name: X_CSI_VXFLEXOS_ENABLELISTVOLUMESNAPSHOT
          value: "false"
        - name: X_CSI_VXFLEXOS_ENABLESNAPSHOTCGDELETE
          value: "false"
        - name: X_CSI_DEBUG
          value: "true"
    #sideCars:
    # Uncomment the following section if you want to run the monitoring sidecar
    #  - name: sdc-monitor
    #    envs:
    #    - name: HOST_PID
    #      value: "1"
    initContainers:
      - image: dellemc/sdc:3.5.1.1
        imagePullPolicy: IfNotPresent
        name: sdc
        envs:
          - name: MDM
            value: "10.xx.xx.xx,10.xx.xx.xx"

    #controller:
    #"controller.nodeSelector" defines what nodes would be selected for pods of controller deployment
    # Leave as blank to use all nodes
    #  nodeSelector:
    #    node-role.kubernetes.io/master: ""
       
    #"controller.tolerations" defines tolerations that would be applied to controller deployment
    # Leave as blank to install controller on worker nodes
    #  tolerations:
    #    - key: "node-role.kubernetes.io/master"
    #      operator: "Exists"
    #      effect: "NoSchedule"
    
    
    storageClass:
      - name: vxflexos
        default: true
        reclaimPolicy: Delete
        allowVolumeExpansion: true
        parameters:
          storagepool: pool1
        allowedTopologies:
        - matchLabelExpressions:
        # Replace X_CSI_VXFLEXOS_SYSTEMNAME with its value
          - key: csi-vxflexos.dellemc.com/X_CSI_VXFLEXOS_SYSTEMNAME     
            values:
            - csi-vxflexos.dellemc.com
      - name: vxflexos-xfs
        default: false
        reclaimPolicy: Delete
        allowVolumeExpansion: true
        parameters:
          storagepool: pool2
          FsType: xfs
        allowedTopologies:
        - matchLabelExpressions:
        # Replace X_CSI_VXFLEXOS_SYSTEMNAME with its value
          - key: csi-vxflexos.dellemc.com/X_CSI_VXFLEXOS_SYSTEMNAME
            values:
            - csi-vxflexos.dellemc.com
    snapshotClass:
      - name: vxflexos-snapclass
