name: Workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  code-check:
    name: Check Go formatting, linting, vetting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Run the formatter, linter, and vetter
        uses: dell/common-github-actions/go-code-formatter-linter-vetter@main
        with:
          directories: ./...
  go_security_scan:
    name: Run gosec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Run gosec to check for security vulnerabilities
        uses: dell/common-github-actions/gosec-runner@main
        with:
          directories: "./..."
          excludes: "G108,G402,G307,G101,G404"
  test:
    name: Run Go unit tests and check package coverage
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.20+
        uses: actions/setup-go@v2
        with:
          go-version: ^1.20
        id: go
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Checkout dell-csi-operator
        uses: actions/checkout@v2
        with:
          repository: 'dell/dell-csi-operator'
          path: 'dell-csi-operator'
      # Not able to use dell common git hub actions as there is
      # no way to skip integration tests currently. And this
      # way of using 'run' to execute run do not allow us to 
      # check for threshold.But it ensures there are no failures
      - name: Run unit tests and check package coverage
        run: make unit-test
  malware_security_scan:
    name: Malware Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Run malware scan
        uses: dell/common-github-actions/malware-scanner@main
        with:
          directories: .
          options: -ri
  image_security_scan:
    name: Image Scanner
    runs-on: ubuntu-latest
    env:
      BASE_IMG : ubuntu:latest
    steps:
      - name: Set up Go 1.20+
        uses: actions/setup-go@v2
        with:
          go-version: ^1.20
        id: go
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build Docker Images
        run: docker build . -t dell-csi-operator:latest
      - name: Scan operator Image
        uses: Azure/container-scan@v0
        env: 
          DOCKLE_HOST: "unix:///var/run/docker.sock"
        with:
          image-name: dell-csi-operator:latest
          severity-threshold: HIGH
